[package]
name = "similar-structs-macros"
description = "Quality-of-life macros for more concise struct/enum definitions"
version = "0.1.0"
authors = ["Evan McPheron"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
